### ISSUE TITLE
Looks promising examples?

### ISSUE THREAD

**Issue by Mrgaton** [sandrohanea/echosharp#3]
Can you put code examples? To transcribe audio from microphone for example.

**Comment by sandrohanea** [comment]
Hey @Mrgaton ,

Currently we have 2 examples:
 - [Transcibing from microphone] (https://github.com/sandrohanea/echosharp/blob/main/examples/EchoSharp.Example.MicrosophoneSpeechTranscript/Program.cs)
 - [Transcribing from a file] (https://github.com/sandrohanea/echosharp/blob/main/examples/EchoSharp.Example.FileSpeechTranscript/Program.cs)
 
 Each of them can use different components for the Speech To Text or Voice Activity Detection.

**Comment by Mrgaton** [comment]
Does it auto downloads models like whisper.net?

**Comment by sandrohanea** [comment]
not all the models can be downloaded directly (some components are even using APIs, not local models), for whisper.net you can download the model using `WhisperGgmlDownloader` .

To run the samples, you can manually download the models or run [this script](https://github.com/sandrohanea/echosharp/blob/main/downloadModels.ps1) that downloads the ones used in the examples and the tests. (but you can use a lot more if you download them manually)

**Comment by sandrohanea** [comment]
> Theses easy libs that auto downloads models and have an easy to use api that have gpu inference are wonderful, you have in mind do the same for llms?

There is a nice possible improvement for EchoSharp. As it focuses on orchestrating different components, it can have a generic option to `PrepareInference`.

In this preparation step, different components can implement their own logic, like downloading the models, ensuring frameworks are installed, warm-up the code, etc.

**Comment by sandrohanea** [comment]
Created a post on the roadmap for this PrepareInference: https://github.com/sandrohanea/echosharp/discussions/4#discussioncomment-11689790

Feel free to upvote it there and comment if more details are needed.

Will close this issue for now.
